### ISSUE TITLE
Can you please  design this using esp32 as microcontroller instead STM one ?

### ISSUE THREAD

**Issue by hemangjoshi37a** [creapunk/CLN17#4]
Can you please design this using esp32 as microcontroller instead STM one ?
https://hjlabs.in/

**Comment by FutureEngineeer** [comment]
Nope, ESP32 is a much poorer choice as a driver controller. However, if you need BLE/Bluetooth/WiFi then you can make an expansion board. I might do it myself if there is a demand for it

**Comment by DRCBR1** [comment]
yes please, we would appreciate it 🙏🏼 
(or any other suggestion (than esp32) to add WiFi)

**Comment by hemangjoshi37a** [comment]
@FutureEngineeer The main problem with STM microcontroller is that is very hard to get in Bharat and even purchasing it from out of Bharat is very costly. Also it lacks WiFi and Bluetooth. I dont understand how is it wrong choice for driver controller. If you can explain what is wrong with esp32 that is done correctly with STM microcontroller.

**Comment by FutureEngineeer** [comment]
STM32G431 costs only $1.7, but it is much faster than ESP32 (about 3 times faster in a comprehensive test). Additionally, STM32 has much more peripherals, it is much more convenient to work with timers, less components are required, much better built-in ADC, much better pin timings. Additionally there are hardware CAN-FD, CORDIC and FPU. 

Collectively, among ESP32/RP2040/STM32G4 microcontrollers, the latter is much better. This microcontroller is available for purchase both through ST.com and through intermediaries like LCSC and others. 

If you need a design without STM32 but only with SP32, you can make it yourself)
