### ISSUE TITLE
Hello, I would like to ask what software was used to draw the interface annotation labels in the "Board Diagram". It looks very beautiful

### ISSUE THREAD

**Issue by xiaotaomcu** [creapunk/CLN17#5]
Hello, I would like to ask what software was used to draw the interface annotation labels in the "Board Diagram". It looks very beautiful

**Comment by xiaotaomcu** [comment]
@FutureEngineeer Thank you very much for your answer. I will learn how to use Inkscape

**Comment by aaronse** [comment]
> [@xiaotaomcu](https://github.com/xiaotaomcu) I used Inkscape, but I think any vector graphics editor can give the same result) You just need to make a stylised block for text and adjust the grid so that when you snap the blocks to the grid, they are arranged in a readable and visually pleasing way

Curious if/how your schematic/PCB illustration/documentation tools have changed now we're in 2025 where AI is used for all the things...

Appreciate that someone asked already in 2023.  Really appreciate this project and the time/effort that's gone into making useful beautiful docs like this.  Very inspiring.  Cheers!
