### ISSUE TITLE
About PB8-BOOT0

### ISSUE THREAD

**Issue by ShenYuan-sean** [creapunk/CLN17#7]
Hello, It seems that you used pb8, which is the boot0 pin, as the CAN_RX function. How does it make sense? Because boot0 needs to be connected to GND for the MCU start-up for internal flash. Looking forward to your reply. TKS

**Comment by FutureEngineeer** [comment]
@ShenYuan-sean

This is a feature of the STM32G4. The joint use of USB and CAN functionality is only possible in this configuration. 

However, this is not a problem. It is enough to set the nBOOT0 optional bit when loading the firmware and this makes it possible to use not the STM pin for bootloader mode, but the internal optional bit nSWBOOT0

I have tested this function and it definitely works
